wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=sto_wd
    ports:
     - "108.160.131.131:80:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=sto_mysql
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
